projects:
  #  '@codelab/core':
  #    schemaPath: packages/core/schema.json
  #    extensions:
  #      endpoints:
  #        dev:
  #          url: 'https://api-uswest.graphcms.com/v1/cjj7mi1rj05uo01cm6q486ov1/master'
  '@codelab':
    schemaPath: packages/auth/schema.json
    excludes:
      - "packages/auth/src/apollo/schema/**/*.graphql"
    extensions:
      endpoints:
        dev:
          url: 'http://localhost:4000/graphql'
