version: '3'
services:
  #  web:
  #    build: .
  #    ports:
  #      - "3000:3000"
  #      - "4000:4000"
  #    volumes:
  #      - .:/app
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
